#!/usr/bin/perl
#
#

$cachedir = "/var/cache/bind";

$first = 1;

if ( -d $cachedir) {

print "[\n";

for (`ls /var/cache/bind | grep zone`) {
($zone) = m/(\S+)/;

print "\t,\n" if not $first;
        $first = 0;

print "\t{ ";
print "\t\t\"{#Zone}\":\"$zone\"\n";
print "\t} ";
}

print "]\n";

}

else {
exit;
}

