#!/usr/bin/perl
#
#

$cachedir = "/var/cache/bind";

$first = 1;

if ( -d $cachedir) {

print "{\"data\":";
print "[\n";

for (`ls /var/cache/bind | grep zone`) {
($zone) = m/(\S+)/;

print "\t," if not $first;
        $first = 0;

print "\t{ ";
print "\t\t\"{#ZONE}\":\"$zone\"";
print "\t}\n ";
}

print "]\n";
print "}";
}

else {
exit;
}
