#!/bin/bash


i=`echo |  openssl s_client -servername $1 -connect $1:443 2>/dev/null | openssl x509 -noout -dates | grep After |awk -F '=' '{print $2}'`

site_date=`date '+%s' -d "$i"`

server_date=`date '+%s'`


expr "$site_date" - "$server_date"
