#!/bin/bash
# PT_BR
# Esse Script compara a data em Epoch do certificado com a data do servidor, é muito útil para antecipar o vencimento 
# de um certificado HTTPS
# EN_US
# This Script compare certificate Epoch date with server date, is very useful to antecipate the past due of the HTTPS certificate
#


i=`echo |  openssl s_client -servername $1 -connect $1:443 2>/dev/null | openssl x509 -noout -dates | grep After |awk -F '=' '{print $2}'`

site_date=`date '+%s' -d "$i"`

server_date=`date '+%s'`


expr "$site_date" - "$server_date"
