#!/bin/bash

#curl -s -w 'Testing Website Response Time for %{url_effective}\n\nLookup Time:\t\t%{time_namelookup}\nConnect Time:\t\t%{time_connect}\nPre-transfer Time:\t%{time_pretransfer}\nStart-transfer Time:\t%{time_starttransfer}\n\nTotal Time:\t\t%{time_total}\n' -o /dev/null $1


#curl -s -w 'Testing Website Response Time for: %{url_effective}\n\nLookup Time:\t\t%{time_namelookup}\nConnect Time:\t\t%{time_connect}\nAppCon Time:\t\t%{time_appconnect}\nRedirect Time:\t\t%{time_redirect}\nPre-transfer Time:\t%{time_pretransfer}\nStart-transfer Time:\t%{time_starttransfer}\n\nTotal Time:\t\t%{time_total}\n' -o /dev/null $1



i=0
i=`curl -ksIL $1 | grep HTTP | tail -1 | awk '{print $2}'`


if [[ "$i" -eq 200 ]]

then
curl -s -m 10 -w '%{time_total}\n' -o /dev/null $1
else
echo "0.1234"
fi
